sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -o Dpkg::Options::=--force-confdef docker-ce
  - docker build -t maruos/dev .

script:
  - docker run maruos/dev /bin/sh -c "ls -al && dpkg -l"
